name: On Push Run

on: push


jobs:
  hello-world:
    name: Hello world
    runs-on: ubuntu-latest
    steps:
    - name: Check-out devops repository
      uses: actions/checkout@v2

    - name: Hello World
      run: python apiTest.py
      shell: sh
