name: API Test

on:
  workflow_run:
    workflows: [Terraform]
    types:
      - completed


jobs:
  hello-world:
    name: Run API Test file
    runs-on: ubuntu-latest
    steps:
    - name: Check-out devops repository
      uses: actions/checkout@v2

    - name: Hello World
      run: python apiTest.py
      shell: sh
